version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - network
  consumer:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    ports:
      - "8081:8081"
    volumes:
      - "/kevink:/wordcloud-consumer"
    networks:
      - network
    depends_on:
      - postgres
networks:
  network:
    name: backend
    external: true
